---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex-trakt-sync
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  values:
    controllers:
      plex-trakt-sync:
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/taxel/plextraktsync
              tag: 0.35.0
            args:
              - watch
            env:
              PLEX_BASEURL: https://plex.kreigan.com
              PLEX_LOCALURL: https://plex.kreigan.com
              PLEX_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: trakt-sync
                    key: PLEX_USERNAME
              TRAKT_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: trakt-sync
                    key: TRAKT_USERNAME
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 5m
                memory: 128M
              limits:
                memory: 512M

    persistence:
      config:
        type: nfs
        path: /volume1/cluster-data/media/plex-trakt-sync
        server: nfs.int.kreigan.com
        advancedMounts:
          plex-trakt-sync:
            app:
              - path: /app/config

      config-yaml:
        type: configMap
        name: plex-trakt-sync
        globalMounts:
          - path: /app/config/config.yml
            subPath: config.yml
            readOnly: true
