---
nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - path: spec/values/persistence/scripts/name
        kind: HelmRelease
      - path: spec/values/persistence/gluetun-scripts/name
        kind: HelmRelease
