---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: storage-memory-usage
spec:
  matchers:
    - name: alertname
      value: NodeMemoryHighUtilization
    - name: instance
      value: nfs.internal.kreigan.com:9100
