---
apiVersion: monitoring.giantswarm.io/v1alpha1
kind: Silence
metadata:
  name: storage-memory-usage
spec:
  matchers:
    - name: alertname
      value: NodeMemoryHighUtilization
      isRegex: false
    - name: instance
      value: nfs.internal.kreigan.com:9100
      isRegex: false
