---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trakt-sync
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: trakt-sync-secret
    creationPolicy: Owner
  data:
    - secretKey: TRAKT_USERNAME
      remoteRef:
        key: Trakt
        property: username
    - secretKey: PLEX_USERNAME
      remoteRef:
        key: Plex
        property: username
