---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: dragonfly-operator
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: false
  dependsOn:
    - name: onepassword-connect
      namespace: external-secrets
  valuesFrom:
    - kind: ConfigMap
      name: dragonfly-operator-helm-values
