---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "kreigan-com"
spec:
  secretName: "kreigan-com-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "kreigan.com"
  dnsNames:
    - "kreigan.com"
    - "*.kreigan.com"
